services:
  bin-it:
    build:
      context: .
    container_name: bin-it
    ports:
      - '8080:8080'
    environment:
      PYTHONUNBUFFERED: 1
      UPRN: ${UPRN}
      MONGO_URI: mongodb://mongodb:27017/
      SMTP_SERVER: smtp.gmail.com
      SMTP_PORT: 587
      GMAIL_APP_PASSWORD: ${APP_PASSWORD}
      SENDER_EMAIL_ADDRESS: ${SENDER}
      RECIPIENT_EMAIL_ADDRESS: ${RECIPIENT}
    depends_on:
      mongodb:
        condition: service_started
    volumes:
      - ./:/bin-it
    networks:
      - bin-it

  mongodb:
    image: mongo:latest
    container_name: bin-it-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data
    networks:
      - bin-it

volumes:
  mongodb-data:

networks:
  bin-it:
    driver: bridge
    name: bin-it
