services:
  bin-it:
    build:
      context: .
      target: production
    container_name: bin-it
    environment:
      PYTHONUNBUFFERED: 1
      UPRN: ${UPRN}
      MONGO_URI: mongodb://mongodb:27017/
      SMTP_SERVER: smtp.gmail.com
      SMTP_PORT: 587
      APP_PASSWORD: ${APP_PASSWORD}
      SENDER: ${SENDER}
      RECIPIENT: ${RECIPIENT}
    depends_on:
      mongodb:
        condition: service_started

  mongodb:
    image: mongo:latest
