services:
  bin-it:
    build:
      context: .
    container_name: bin-it
    ports:
      - '8080:8080'
    environment:
      PYTHONUNBUFFERED: 1
      UPRN: ${UPRN}
      MONGO_URI: mongodb://mongodb:27017/
      SMTP_SERVER: smtp.gmail.com
      SMTP_PORT: 587
      GMAIL_APP_PASSWORD: ${GMAIL_APP_PASSWORD}
      SENDER_EMAIL_ADDRESS: ${SENDER_EMAIL_ADDRESS}
      RECIPIENT_EMAIL_ADDRESS: ${RECIPIENT_EMAIL_ADDRESS}
      NTFY_ALERTS_TOPIC: ${NTFY_ALERTS_TOPIC:-bin-it-alerts}
    depends_on:
      ntfy:
        condition: service_healthy
      mongodb:
        condition: service_started
    volumes:
      - ./:/bin-it
    networks:
      - bin-it

  ntfy:
    image: binwiederhier/ntfy
    container_name: bin-it-ntfy
    command:
      - serve
    environment:
      NTFY_BASE_URL: http://ntfy.example.com
      NTFY_CACHE_FILE: /var/lib/ntfy/cache.db
      NTFY_AUTH_FILE: /var/lib/ntfy/auth.db
      NTFY_AUTH_DEFAULT_ACCESS: deny-all
      NTFY_BEHIND_PROXY: true
      NTFY_ATTACHMENT_CACHE_DIR: /var/lib/ntfy/attachments
      NTFY_ENABLE_LOGIN: true
      NTFY_UPSTREAM_BASE_URL: https://ntfy.sh
    volumes:
      - ./:/var/lib/ntfy
    ports:
      - 8093:80
    healthcheck:
      test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    init: true

  mongodb:
    image: mongo:latest
    container_name: bin-it-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data
    networks:
      - bin-it

volumes:
  mongodb-data:

networks:
  bin-it:
    driver: bridge
    name: bin-it
